FROM openjdk:17-jdk-slim
LABEL maintainer="saiharinadhpv@gmail.com"
COPY target/ecommerce-backend-0.0.1-SNAPSHOT.jar.original /app/ecommerce-backend-0.0.1-SNAPSHOT.jar.original
WORKDIR /app
ENTRYPOINT ["java", "-jar", "/target/ ecommerce-backend-0.0.1-SNAPSHOT.jar.original"]
