FROM openjdk:17-jdk-slim
LABEL maintainer="saiharinadhpv@gmail.com"
COPY target/ecommerce-backend-0.0.1-SNAPSHOT.jar /app/ecommerce-backend-0.0.1-SNAPSHOT.jar
WORKDIR /app
ENTRYPOINT ["java", "-jar", "/target/ ecommerce-backend-0.0.1-SNAPSHOT.jar"]
